export const posts = [{picture: "../assets/profile pics/lindsay.jpg", name: "Lindsay Jones", verified: false, time: "1 hour ago", location: "Rincon Bike Trail, Venture County", image: false, icon: "bike", workoutType: "Outdoor Cycle", fitnessTracker: "gearfit", totalTime: "0:51:39", totalCalories: "346cal", distance: "10.53km", heartRate: null, caption: "Excuses don't burn calories!", likes:"2,679", comments: "20", liked: false, postID: "0"}, 
{picture: "", name: "Daniel Kelly", verified: true, time: "3 hours ago", location: "Tenerife Top Training", image: true, icon: "swim", workoutType: "Pool Swim", fitnessTracker: "fitbit", totalTime: "2:26:09", totalCalories: "1452cal", distance: "7.30km", heartRate: null, caption: "It's been a long comeback. Things were pretty dark for me. But I have a faith now, and it saves my day. I was...", likes:"108K", comments: "298", liked: true, postID: "1"},
{picture: "", 
name: "Greta Costa", 
verified: false, 
time: "5 hours ago", 
location: "A.S.D Gymnos", 
image: false, 
icon: "yoga", 
workoutType: "Yoga", 
fitnessTracker: "apple", 
totalTime: "1:03:45", 
totalCalories: "569cal", 
distance: null, 
heartRate: "968BPM", 
caption: null, 
likes: 97, 
comments: 2, 
liked: true, 
postID: "2"} ]